@echo off
call "%~dp0_Batch\processDir.bat" "%~dp0Delphi Code\QuerySystemMenu"
call "%~dp0_Batch\processDir.bat" "%~dp0Delphi Code\DragNDropDlgs"
call "%~dp0_Batch\processDir.bat" "%~dp0Delphi Code\ParamUtils"
call "%~dp0_Batch\processDir.bat" "%~dp0_Common"
call "%~dp0_Batch\processDir.bat" "%~dp0Base-Converter"
call "%~dp0_Batch\processDir.bat" "%~dp0Batch-Working-Directory"
call "%~dp0_Batch\processDir.bat" "%~dp0CmdHere"
call "%~dp0_Batch\processDir.bat" "%~dp0Create Shortcut"
call "%~dp0_Batch\processDir.bat" "%~dp0DNDFC (Drag'n'Drop FileCompare)"
call "%~dp0_Batch\processDir.bat" "%~dp0DosLineConv"
call "%~dp0_Batch\processDir.bat" "%~dp0FileExtCh"
call "%~dp0_Batch\processDir.bat" "%~dp0FileMD5"
call "%~dp0_Batch\processDir.bat" "%~dp0Kalenderersatz"
call "%~dp0_Batch\processDir.bat" "%~dp0Recycle Bin Unit"
call "%~dp0_Batch\processDir.bat" "%~dp0Recycle Bin Unit\Windows 95 Bit Bucket Reader"
call "%~dp0_Batch\processDir.bat" "%~dp0Uhrersatz (Atomuhr)"
call "%~dp0_Batch\processDir.bat" "%~dp0Units"
call "%~dp0_Batch\processDir.bat" "%~dp0umlaut-Ersetzer"
call "%~dp0_Batch\processDir.bat" "%~dp0Dreisatz"
call "%~dp0_Batch\processDir.bat" "%~dp0SignExample"
call "%~dp0_Batch\processDir.bat" "%~dp0"

call "%~dp0_Batch\processDir.bat" "%~dp0StatusMon 3.0\Dll-Test"
call "%~dp0_Batch\processDir.bat" "%~dp0StatusMon 3.0"

"C:\Programme\Inno Setup 5\iscc.exe" "%~dp0StatusMon 3.0\StatusMon.iss"

call "%~dp0_Batch\processDir.bat" "%~dp0StatusMon 3.0\Output"
