@echo off
call cleanDir.bat "_Common"
call cleanDir.bat "Batch-Working-Directory"
call cleanDir.bat "CmdHere"
call cleanDir.bat "Create Shortcut"
call cleanDir.bat "DNDFC (Drag'n'Drop FileCompare)"
call cleanDir.bat "DosLineConv"
call cleanDir.bat "FileExtCh"
call cleanDir.bat "FileMD5"
call cleanDir.bat "Kalenderersatz"
call cleanDir.bat "Recycle Bin Unit"
call cleanDir.bat "Recycle Bin Unit\Windows 95 Bit Bucket Reader"
call cleanDir.bat "Uhrersatz (Atomuhr)"
call cleanDir.bat "Units"
call cleanDir.bat "umlaut-Ersetzer"
call cleanDir.bat "Dreisatz"
call cleanDir.bat "."
