USE [ZEITERFASSUNG]
GO

/****** Object:  Table [dbo].[REGELARBEITSZEIT]    Script Date: 15.02.2019 15:15:56 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[REGELARBEITSZEIT](
	[USERNAME] [varchar](100) NOT NULL,
	[MINUTEN] [int] NOT NULL,
 CONSTRAINT [PK_REGELARBEITSZEIT] PRIMARY KEY CLUSTERED 
(
	[USERNAME] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO


